// package countrycodestring
// Code generated : DO NOT EDIT MANUALLY: 2025-02-08T10:03:38Z
package countrycodestring

// CC ...
var CC = map[string]int32{
	"Angola":                            24,
	"Botswana":                          72,
	"Bouvet Island":                     74,
	"Brazil":                            76,
	"Belize":                            84,
	"British Indian Ocean Territory":    86,
	"Solomon Islands":                   90,
	"Virgin Islands (British)":          92,
	"Brunei Darussalam":                 96,
	"Bulgaria":                          100,
	"Myanmar":                           104,
	"Burundi":                           108,
	"Belarus":                           112,
	"Cambodia":                          116,
	"Cameroon":                          120,
	"Canada":                            124,
	"Cabo Verde":                        132,
	"Cayman Islands":                    136,
	"Central African Republic":          140,
	"Sri Lanka":                         144,
	"Chad":                              148,
	"Chile":                             152,
	"China":                             156,
	"Taiwan  Province of China":         158,
	"Christmas Island":                  162,
	"Cocos (Keeling) Islands":           166,
	"Colombia":                          170,
	"Comoros":                           174,
	"Mayotte":                           175,
	"Congo":                             178,
	"Congo  Democratic Republic of the": 180,
	"Cook Islands":                      184,
	"Costa Rica":                        188,
	"Croatia":                           191,
	"Cuba":                              192,
	"Cyprus":                            196,
	"Czechia":                           203,
	"Benin":                             204,
	"Bosnia and Herzegovina":            70,
	"Denmark":                           208,
	"Dominican Republic":                214,
	"Ecuador":                           218,
	"El Salvador":                       222,
	"Equatorial Guinea":                 226,
	"Ethiopia":                          231,
	"Dominica":                          212,
	"Eritrea":                           232,
	"Estonia":                           233,
	"Faroe Islands":                     234,
	"Falkland Islands (Malvinas)":       238,
	"Fiji":                              242,
	"Finland":                           246,
	"Åland Islands":                     248,
	"France":                            250,
	"French Guiana":                     254,
	"French Polynesia":                  258,
	"French Southern Territories":       260,
	"Djibouti":                          262,
	"Gabon":                             266,
	"Georgia":                           268,
	"Gambia":                            270,
	"Palestine  State of":               275,
	"Germany":                           276,
	"Ghana":                             288,
	"South Georgia and the South Sandwich Islands": 239,
	"Kiribati":                               296,
	"Greece":                                 300,
	"Gibraltar":                              292,
	"Greenland":                              304,
	"Grenada":                                308,
	"Guadeloupe":                             312,
	"Guam":                                   316,
	"Guatemala":                              320,
	"Guinea":                                 324,
	"Guyana":                                 328,
	"Haiti":                                  332,
	"Heard Island and McDonald Islands":      334,
	"Holy See":                               336,
	"Honduras":                               340,
	"Hong Kong":                              344,
	"Iceland":                                352,
	"India":                                  356,
	"Indonesia":                              360,
	"Iran  Islamic Republic of":              364,
	"Iraq":                                   368,
	"Ireland":                                372,
	"Israel":                                 376,
	"Italy":                                  380,
	"Côte d'Ivoire":                          384,
	"Jamaica":                                388,
	"Japan":                                  392,
	"Kazakhstan":                             398,
	"Jordan":                                 400,
	"Kenya":                                  404,
	"Korea  Democratic People's Republic of": 408,
	"Kuwait":                                 414,
	"Kyrgyzstan":                             417,
	"Korea  Republic of":                     410,
	"Lao People's Democratic Republic":       418,
	"Lebanon":                                422,
	"Lesotho":                                426,
	"Latvia":                                 428,
	"Liberia":                                430,
	"Libya":                                  434,
	"Liechtenstein":                          438,
	"Lithuania":                              440,
	"Luxembourg":                             442,
	"Macao":                                  446,
	"Madagascar":                             450,
	"Malawi":                                 454,
	"Malaysia":                               458,
	"Maldives":                               462,
	"Mali":                                   466,
	"Malta":                                  470,
	"Martinique":                             474,
	"Mauritania":                             478,
	"Mauritius":                              480,
	"Mexico":                                 484,
	"Monaco":                                 492,
	"Mongolia":                               496,
	"Moldova  Republic of":                   498,
	"Montenegro":                             499,
	"Montserrat":                             500,
	"Morocco":                                504,
	"Mozambique":                             508,
	"Oman":                                   512,
	"Namibia":                                516,
	"Nauru":                                  520,
	"Nepal":                                  524,
	"Hungary":                                348,
	"Netherlands  Kingdom of the":            528,
	"Sint Maarten (Dutch part)":              534,
	"Bonaire  Sint Eustatius and Saba":       535,
	"Curaçao":                                531,
	"New Caledonia":                          540,
	"Vanuatu":                                548,
	"New Zealand":                            554,
	"Nicaragua":                              558,
	"Niger":                                  562,
	"Nigeria":                                566,
	"Niue":                                   570,
	"Norfolk Island":                         574,
	"Norway":                                 578,
	"Northern Mariana Islands":               580,
	"United States Minor Outlying Islands":   581,
	"Aruba":                                  533,
	"Micronesia  Federated States of":        583,
	"Pakistan":                               586,
	"Palau":                                  585,
	"Panama":                                 591,
	"Marshall Islands":                       584,
	"Paraguay":                               600,
	"Peru":                                   604,
	"Philippines":                            608,
	"Pitcairn":                               612,
	"Poland":                                 616,
	"Portugal":                               620,
	"Guinea-Bissau":                          624,
	"Timor-Leste":                            626,
	"Puerto Rico":                            630,
	"Qatar":                                  634,
	"Romania":                                642,
	"Russian Federation":                     643,
	"Réunion":                                638,
	"Rwanda":                                 646,
	"Saint Barthélemy":                       652,
	"Saint Helena  Ascension and Tristan da Cunha": 654,
	"Saint Kitts and Nevis":                        659,
	"Anguilla":                                     660,
	"Saint Lucia":                                  662,
	"Saint Martin (French part)":                   663,
	"Saint Pierre and Miquelon":                    666,
	"San Marino":                                   674,
	"Sao Tome and Principe":                        678,
	"Saint Vincent and the Grenadines":             670,
	"Saudi Arabia":                                 682,
	"Senegal":                                      686,
	"Serbia":                                       688,
	"Seychelles":                                   690,
	"Sierra Leone":                                 694,
	"Singapore":                                    702,
	"Slovakia":                                     703,
	"Viet Nam":                                     704,
	"Somalia":                                      706,
	"South Africa":                                 710,
	"Slovenia":                                     705,
	"Zimbabwe":                                     716,
	"Spain":                                        724,
	"South Sudan":                                  728,
	"Sudan":                                        729,
	"Western Sahara":                               732,
	"Suriname":                                     740,
	"Svalbard and Jan Mayen":                       744,
	"Eswatini":                                     748,
	"Sweden":                                       752,
	"Switzerland":                                  756,
	"Tajikistan":                                   762,
	"Syrian Arab Republic":                         760,
	"Thailand":                                     764,
	"Togo":                                         768,
	"Tokelau":                                      772,
	"Tonga":                                        776,
	"Trinidad and Tobago":                          780,
	"United Arab Emirates":                         784,
	"Tunisia":                                      788,
	"Türkiye":                                      792,
	"Turkmenistan":                                 795,
	"Turks and Caicos Islands":                     796,
	"Tuvalu":                                       798,
	"Uganda":                                       800,
	"Ukraine":                                      804,
	"North Macedonia":                              807,
	"Egypt":                                        818,
	"United Kingdom of Great Britain and Northern Ireland": 826,
	"Guernsey":                          831,
	"Jersey":                            832,
	"Isle of Man":                       833,
	"Tanzania  United Republic of":      834,
	"United States of America":          840,
	"Virgin Islands (U.S.)":             850,
	"Burkina Faso":                      854,
	"Uruguay":                           858,
	"Venezuela  Bolivarian Republic of": 862,
	"Wallis and Futuna":                 876,
	"Uzbekistan":                        860,
	"Samoa":                             882,
	"Yemen":                             887,
	"Zambia":                            894,
	"Papua New Guinea":                  598,
	"Bangladesh":                        50,
	"Armenia":                           51,
	"Barbados":                          52,
	"Austria":                           40,
	"Belgium":                           56,
	"Bahrain":                           48,
	"Bermuda":                           60,
	"Australia":                         36,
	"Bhutan":                            64,
	"Bolivia  Plurinational State of":   68,
	"Antarctica":                        10,
	"Afghanistan":                       4,
	"Bahamas":                           44,
	"American Samoa":                    16,
	"Albania":                           8,
	"Algeria":                           12,
	"Andorra":                           20,
	"Azerbaijan":                        31,
	"Antigua and Barbuda":               28,
	"Argentina":                         32,
}
